state_name: Assam
state_key: assam
discovered_at: '2025-12-31T00:36:41.633500'
sections:
  hazard:
    name: Hazard
    indicators: []
  exposure:
    name: Exposure
    indicators: []
  vulnerability:
    name: Vulnerability
    indicators: []
  government_response:
    name: Government Response
    indicators: []
