state_name: Bihar
state_key: bihar
discovered_at: '2025-12-31T00:39:30.503530'
sections:
  hazard:
    name: Hazard
    indicators: []
  exposure:
    name: Exposure
    indicators: []
  vulnerability:
    name: Vulnerability
    indicators: []
  government_response:
    name: Government Response
    indicators: []
