state_name: Odisha
state_key: odisha
discovered_at: '2026-09-25T20:33:32.412023'
sections:
  hazard:
    name: Hazard
    indicators:
    - name: Mean Elevation
      key: mean_elevation
      position: 1
      enabled: true
      section: Hazard
    - name: Distance from the river
      key: distance_from_the_river
      position: 2
      enabled: true
      section: Hazard
    - name: Average Distance from the Sea
      key: average_distance_from_the_sea
      position: 3
      enabled: true
      section: Hazard
    - name: Mean Runoff
      key: mean_runoff
      position: 4
      enabled: true
      section: Hazard
    - name: Total Runoff per month
      key: total_runoff_per_month
      position: 5
      enabled: true
      section: Hazard
    - name: Highest Daily Runoff
      key: highest_daily_runoff
      position: 6
      enabled: true
      section: Hazard
    - name: Total Monthly Rainfall
      key: total_monthly_rainfall
      position: 7
      enabled: true
      section: Hazard
    - name: Mean slope
      key: mean_slope
      position: 8
      enabled: true
      section: Hazard
    - name: Drainage density
      key: drainage_density
      position: 9
      enabled: true
      section: Hazard
  exposure:
    name: Exposure
    indicators:
    - name: Total Number of Households
      key: total_number_of_households
      position: 1
      enabled: true
      section: Exposure
    - name: Population
      key: population
      position: 2
      enabled: true
      section: Exposure
  vulnerability:
    name: Vulnerability
    indicators:
    - name: Average Availablity of Domestic Electricity
      key: average_availablity_of_domestic_electricity
      position: 1
      enabled: true
      section: Vulnerability
    - name: Percentage of Households with Piped Water Connection
      key: percentage_of_households_with_piped_water_connection
      position: 2
      enabled: true
      section: Vulnerability
    - name: Percentage of Households Without Sanitation Facilities
      key: percentage_of_households_without_sanitation_facilities
      position: 3
      enabled: true
      section: Vulnerability
    - name: Elderly Population
      key: elderly_population
      position: 4
      enabled: true
      section: Vulnerability
    - name: Children Population
      key: children_population
      position: 5
      enabled: true
      section: Vulnerability
    - name: 'Human Lives Lost : Flood and Cyclone'
      key: human_lives_lost_flood_and_cyclone
      position: 6
      enabled: true
      section: Vulnerability
    - name: Population Affected by Flood and Cyclone
      key: population_affected_by_flood_and_cyclone
      position: 7
      enabled: true
      section: Vulnerability
    - name: Cultivated Area Affected by Flood and Cyclone
      key: cultivated_area_affected_by_flood_and_cyclone
      position: 8
      enabled: true
      section: Vulnerability
  government_response:
    name: Government Response
    indicators:
    - name: 'Preparedness Measures Flood Tenders : Total Value'
      key: preparedness_measures_flood_tenders_total_value
      position: 1
      enabled: true
      section: Government Response
    - name: 'Immediate Measure Flood Tenders : Total Value'
      key: immediate_measure_flood_tenders_total_value
      position: 2
      enabled: true
      section: Government Response
    - name: 'Flood tenders Under RIDF Scheme : Total Value'
      key: flood_tenders_under_ridf_scheme_total_value
      position: 3
      enabled: true
      section: Government Response
