discovery_timestamp: '2025-12-31T00:52:51.207977'
total_states: 5
states:
  assam:
    name: Assam
    config_file: assam.yaml
    total_indicators: 0
    sections:
      hazard: 0
      exposure: 0
      vulnerability: 0
      government_response: 0
